---
all:
  children:
    windows:
      children:
        staging_nodes:
          hosts:
            ue-staging-01:
              ansible_host: 192.168.1.14
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5985
