---
all:
  children:
    # --- Windows VMs ---
    windows:
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5985
        ansible_become: true
        ansible_become_method: runas
        ansible_become_user: "{{ ansible_user }}"
        ansible_become_password: "{{ ansible_password }}"

    # --- Linux ---
    # Proxmox hosts are managed via Terraform (ansible_inventory.tf)
    linux:
      children:
        optik:
          hosts:
            optik-01:
              ansible_host: 192.168.1.xxx
        pulse_admin:
          hosts:
            pulse-admin:
              ansible_host: 192.168.1.70
              ansible_connection: local
        sonic:
          hosts:
            sonic-switch-01:
              ansible_host: 192.168.1.5
              ansible_user: admin
          vars:
            ansible_become: true
            ansible_become_method: sudo
        rship:
          hosts:
            rship-01:
              ansible_host: 192.168.1.xxx
            rship-02:
              ansible_host: 192.168.1.xxx
            rship-03:
              ansible_host: 192.168.1.xxx
