---
# Example inventory — copy this directory to create a new deployment environment
#
# Usage:
#   cp -r inventories/example inventories/mysite
#   # Edit inventories/mysite/hosts.yml with your hosts
#   ansible-playbook playbooks/site.yml -i inventories/mysite/hosts.yml

all:
  children:
    # --- Windows VMs ---
    windows:
      children:
        ue_nodes:
          hosts:
            # windows-unreal-01:
            #   ansible_host: 192.168.1.100
            #   rivermax: true
            #   media_ip: "10.0.0.1"      # CX6 VF — SMPTE 2110 media
            # windows-unreal-02:
            #   ansible_host: 192.168.1.101
            #   rivermax: false
          vars: {}
        arnold_nodes:
          hosts: {}
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5985

    # --- Linux VMs ---
    linux_vms:
      children:
        optik:
          hosts: {}
        manager:
          hosts:
            # control-plane-01:
            #   ansible_host: 192.168.1.200
            #   ansible_connection: local
          vars: {}

    # --- LXC Containers ---
    lxc:
      children:
        rship_nodes:
          hosts: {}
        rship_control:
          hosts: {}

    # --- Convenience meta-groups ---
    linux:
      children:
        linux_vms:
        lxc:
