---
- name: Apply netplan
  ansible.builtin.command:
    argv: [netplan, apply]
  changed_when: true

- name: Bring up SMB interface
  ansible.builtin.command:
    argv:
      - ifup
      - "{{ smb_interface | trim }}"
  changed_when: true
