---
all:
  children:
    # --- Windows VMs ---
    windows:
      children:
        ue_nodes:
          hosts:
            windows-unreal-01:
              ansible_host: 192.168.1.169
              rivermax: true
            windows-unreal-02:
              ansible_host: 192.168.1.150
              rivermax: true
            windows-unreal-03:
              ansible_host: 192.168.1.159
              rivermax: true
            windows-unreal-04:
              ansible_host: 192.168.1.161
              rivermax: true
            windows-unreal-05:
              ansible_host: 192.168.1.166
              rivermax: true
            windows-unreal-dev-01:
              ansible_host: 192.168.1.112
              rivermax: false
            windows-unreal-dev-02:
              ansible_host: 192.168.1.118
              rivermax: false
        arnold_nodes:
          hosts:
            windows-arnold-01:
              ansible_host: 192.168.1.xxx
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5985

    # --- Linux VMs ---
    linux_vms:
      children:
        optik:
          hosts:
            optik-01:
              ansible_host: 192.168.1.xxx
        manager:
          hosts:
            ue-control-plane-01:
              ansible_host: 192.168.1.168
              ansible_connection: local

    # --- LXC Containers ---
    lxc:
      children:
        rship_nodes:
          hosts:
            rship-01:
              ansible_host: 192.168.1.xxx
            rship-02:
              ansible_host: 192.168.1.xxx
            rship-03:
              ansible_host: 192.168.1.xxx
        rship_control:
          hosts:
            rship-cp-01:
              ansible_host: 192.168.1.xxx

    # --- Convenience meta-groups ---
    linux:
      children:
        linux_vms:
        lxc:
