---
all:
  children:
    # --- Windows VMs ---
    windows:
      children:
        ue_nodes:
          children:
            content_nodes:
              hosts:
                windows-unreal-render-01:
                  ansible_host: 192.168.1.71
                  rivermax: true
                  media_ip: "10.0.0.1"
                  ndisplay_primary: true
                  ndisplay_node: "Node_1"
                windows-unreal-render-02:
                  ansible_host: 192.168.1.72
                  rivermax: true
                  media_ip: "10.0.0.2"
                  ndisplay_node: "Node_2"
                windows-unreal-render-03:
                  ansible_host: 192.168.1.73
                  rivermax: true
                  media_ip: "10.0.0.3"
                  ndisplay_node: "Node_3"
                windows-unreal-render-04:
                  ansible_host: 192.168.1.74
                  rivermax: true
                  media_ip: "10.0.0.4"
                  ndisplay_node: "Node_4"
            previs_nodes:
              hosts:
                windows-unreal-render-05:
                  ansible_host: 192.168.1.75
                  rivermax: true
                  media_ip: "10.0.0.5"
            # windows-unreal-dev-01:
            #   ansible_host: 192.168.1.112
            #   rivermax: false
            # windows-unreal-dev-02:
            #   ansible_host: 192.168.1.118
            #   rivermax: false
            # windows-unreal-build-01:
            #   ansible_host: 192.168.1.119
            #   rivermax: false
        touch_nodes:
          hosts:
            windows-touch-01:
              ansible_host: 192.168.1.76
              rivermax: true
              media_ip: "10.0.0.6"
        # arnold_nodes:
        #   hosts:
        #     windows-arnold-render-01:
        #       ansible_host: 192.168.1.xxx
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5985

    # --- Linux VMs ---
    linux_vms:
      children:
        optik:
          hosts:
            optik-01:
              ansible_host: 192.168.1.xxx
        manager:
          hosts:
            ue-control-plane-01:
              ansible_host: 192.168.1.168
              ansible_connection: local

    # --- LXC Containers ---
    lxc:
      children:
        rship_nodes:
          hosts:
            rship-01:
              ansible_host: 192.168.1.xxx
            rship-02:
              ansible_host: 192.168.1.xxx
            rship-03:
              ansible_host: 192.168.1.xxx
        rship_control:
          hosts:
            rship-cp-01:
              ansible_host: 192.168.1.xxx

    # --- Convenience meta-groups ---
    linux:
      children:
        linux_vms:
        lxc:
