---
# HRNYC inventory — NYC production environment
#
# Usage:
#   ansible-playbook playbooks/site.yml -i inventories/hrnyc/hosts.yml

all:
  children:
    # --- Windows ---
    windows:
      children:
        ue:
          children:
            ue_content:
              hosts: {}
            ue_previs:
              hosts: {}
            ue_staging:
              hosts: {}
            ue_build:
              hosts: {}
        touch:
          hosts: {}
        arnold_fusion:
          hosts: {}
        workstation:
          hosts: {}
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
        ansible_port: 5985

    # --- Linux ---
    linux:
      children:
        optik:
          hosts: {}
        pixelfarm:
          hosts: {}
        rship:
          hosts: {}
        rustdesk:
          hosts: {}
        pulse_admin:
          hosts: {}
